// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARAcYr2fRAu4WCwdsPvidyO_qQ-R0JO0U',
    appId: '1:146848322750:web:cc1d9a14cf0e93022ffaef',
    messagingSenderId: '146848322750',
    projectId: 'gem-app-2adf0',
    authDomain: 'gem-app-2adf0.firebaseapp.com',
    storageBucket: 'gem-app-2adf0.appspot.com',
    measurementId: 'G-50SRLM3PCV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7UkkioCkVPmSzR9fZrA3JpSiUA4MRz3E',
    appId: '1:146848322750:android:3a2e04f2737a5dbb2ffaef',
    messagingSenderId: '146848322750',
    projectId: 'gem-app-2adf0',
    storageBucket: 'gem-app-2adf0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYx1VNliQIkxwlfEw-b5xFtEGeeS6Kvu0',
    appId: '1:146848322750:ios:b1ec986d8bd214f82ffaef',
    messagingSenderId: '146848322750',
    projectId: 'gem-app-2adf0',
    storageBucket: 'gem-app-2adf0.appspot.com',
    iosBundleId: 'com.example.geminiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYx1VNliQIkxwlfEw-b5xFtEGeeS6Kvu0',
    appId: '1:146848322750:ios:b1ec986d8bd214f82ffaef',
    messagingSenderId: '146848322750',
    projectId: 'gem-app-2adf0',
    storageBucket: 'gem-app-2adf0.appspot.com',
    iosBundleId: 'com.example.geminiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARAcYr2fRAu4WCwdsPvidyO_qQ-R0JO0U',
    appId: '1:146848322750:web:5bef98f2149b83bc2ffaef',
    messagingSenderId: '146848322750',
    projectId: 'gem-app-2adf0',
    authDomain: 'gem-app-2adf0.firebaseapp.com',
    storageBucket: 'gem-app-2adf0.appspot.com',
    measurementId: 'G-Y5M0N37JK2',
  );
}
